### ISSUE TITLE
 user_id问题

### ISSUE THREAD

**Issue by holk-h** [noneplugin/nonebot-plugin-chatrecorder#38]
请问更新后，获取聊天记录时，MessageRecord 对象没有存每条消息的用户 id 了吗？

**Comment by he0119** [comment]
用户 ID 保存在 session 里的。

https://github.com/noneplugin/nonebot-plugin-session

**Comment by holk-h** [comment]
> 用户 ID 保存在 session 里的。你可以通过 session_persist_id 来获取对应的用户 ID。
> 
> https://github.com/noneplugin/nonebot-plugin-session
> 
> https://github.com/noneplugin/nonebot-plugin-chatrecorder/blob/8e98684438c1c591875fcfec09542dc813540b00/nonebot_plugin_chatrecorder/record.py#L142

已解决，感谢
