### ISSUE TITLE
第一次用却显示更新数据库失败

### ISSUE THREAD

**Issue by NAOLIU** [noneplugin/nonebot-plugin-chatrecorder#39]
python 3.11.8
Nonebot应该是最新的那版
系统是Win10
安装好插件后，nb run报错：
![image](https://github.com/noneplugin/nonebot-plugin-chatrecorder/assets/55797625/0ba4851d-fc3a-4856-821b-6276a2af16de)
随后运行 nb orm upgrade：
![image](https://github.com/noneplugin/nonebot-plugin-chatrecorder/assets/55797625/ef0c68e8-daa2-4014-95b8-045ba7ce1fa1)
把fastapi改为 fastapi+aiohttp，再运行一次：
![image](https://github.com/noneplugin/nonebot-plugin-chatrecorder/assets/55797625/d1c8a65a-9c2d-4809-a918-cd4fc9d85a66)
不是，这Mirai_qq什么鬼XDDDDDDDD，我没用Mirai

**Comment by MeetWq** [comment]
你是不是装的时候选了 mirai 适配器？可以在 pyproject.toml 文件中修改

**Comment by NAOLIU** [comment]
> 你是不是装的时候选了 mirai 适配器？可以在 pyproject.toml 文件中修改

应该有装，但是没有用到，我不清楚有没有影响，当时以防万一装了不少适配器
![image](https://github.com/noneplugin/nonebot-plugin-chatrecorder/assets/55797625/e6790a3b-b49b-4af9-a57a-74667b4e6a14)

**Comment by NAOLIU** [comment]
我删掉之后是这样：
![image](https://github.com/noneplugin/nonebot-plugin-chatrecorder/assets/55797625/a212b87e-a130-479f-9ba9-259e474d2574)
然后我重新nb orm upgrad，显示如下报错：
![image](https://github.com/noneplugin/nonebot-plugin-chatrecorder/assets/55797625/04a1cd07-35a1-4dab-8a8c-5279425324f5)

**Comment by NAOLIU** [comment]
我以为我删的不够干净，我用nb adapter uninstall nonebot.adapters.mirai2卸载，但还是一样报错
![image](https://github.com/noneplugin/nonebot-plugin-chatrecorder/assets/55797625/be26b2cd-f8f2-4413-8693-fcc3a34154d8)

**Comment by NAOLIU** [comment]
没事了，我刚刚逐个测试出来，貌似跟nonebot.adapters.bilibili这个适配器也是不兼容
我删掉nonebot.adapters.bilibili之后就正常能进行升级了

**Comment by MeetWq** [comment]
用到什么适配器再填什么即可，很多适配器是需要额外配置环境变量的，并不是不兼容

另外这些问题和这个插件没什么关系，可以去 nonebot 的群里问
