### ISSUE TITLE
请问在0.6.0版本中使用orm插件的情况下，是否有办法更改聊天记录存储位置

### ISSUE THREAD

**Issue by luosheng520qaq** [noneplugin/nonebot-plugin-chatrecorder#48]
如题，有办法修改windows系统下运行改插件时修改数据库位置吗？不想放C盘

**Comment by MeetWq** [comment]
orm 默认使用 sqlite 数据库，存放在 [localstore 插件定义的 data path](https://github.com/nonebot/plugin-localstore#data-path)

Windows 下是这样的位置：
```
C:\Users\<username>\AppData\Local\nonebot2\nonebot-plugin-orm\db.sqlite3
```

你可以通过修改 localstore 插件的 `localstore_data_dir` 配置项来改变 **所有使用 localstore 的插件的数据存放位置**
如：
```
localstore_data_dir="F:/testbot"
```

如果你只想改 sqlite 数据库的位置，可以修改 orm 插件的 `sqlalchemy_database_url` 配置项，修改为如下形式：
```
sqlite+aiosqlite:///<db_path>
```
如：
```
sqlalchemy_database_url="sqlite+aiosqlite:///F:/testbot/data.db"
```

**Comment by luosheng520qaq** [comment]
非常感谢解答
