### ISSUE TITLE
无法获取会话的机器人消息 | Can't get bot's message records in 0.7.0

### ISSUE THREAD

**Issue by zhtg-cxxc** [noneplugin/nonebot-plugin-chatrecorder#65]
### 问题描述

执行以下代码的时候，在使用 `Console` 和 `Telegram` 适配器时，不会输出任何（机器人自己发出的）的历史消息，即使已经在 `.env` 设置了 `chatrecorder_record_send_msg=true`，并且直接访问数据库是能看到机器人发送的消息的记录的。移除 `types=['message_sent'],` 后能正常显示用户的历史消息。

```python
chat = on_message(rule=to_me(), priority=10)

@chat.handle()
async def handle_chat(session: Uninfo):
    msgs = await get_message_records(
        session=session,
        types=['message_sent'],
        time_start=datetime.now(timezone.utc) - timedelta(days=1),
    )
    logger.info(str())
    await chat.finish("历史消息：\n" + "\n".join([str(i.id) + ":" + i.plain_text for i in msgs]))
```

![数据库能正常记录，并且这个数据库已经清空了一遍，消息是刚记录下来的](https://github.com/user-attachments/assets/ee557ed4-7ab5-4e50-a647-0b519f080fdb)

猜测是同一个会话中，机器人 `message_sent` 的 `session_persist_id` 与用户发出的 `message` 的 `session_persist_id` 不同，但插件代码Query仅设定了 `message` 的 `session_persist_id` 所致。由于最近刚把自己的项目升到0.7.0，之前没有使用 `nonebot-plugin-uninfo` 的时候是没有这个问题的，所以也在边写issue边找问题，如果是别的地方出问题了也还请见谅。

https://github.com/noneplugin/nonebot-plugin-chatrecorder/blob/3a22028df45d08f34f4c5e01ffdcabb3162e5444/nonebot_plugin_chatrecorder/record.py#L195

### 运行环境

（环境是新建的，所有的插件均在issue提交当日使用 `pip` 或 `nb plugin` 直接安装最新版本）

```bash
(.conda) > pip list
...
nb-cli                      1.4.2
nonebot-adapter-console     0.6.0
nonebot-adapter-onebot      2.4.6
nonebot-adapter-telegram    0.1.0b20
nonebot_plugin_chatrecorder 0.7.0
nonebot-plugin-localstore   0.7.3
nonebot-plugin-orm          0.7.6
nonebot_plugin_session      0.3.2
nonebot-plugin-uninfo       0.6.3
nonebot2                    2.4.1
nonechat                    0.3.0
noneprompt                  0.1.9
nonestorage                 0.1.0
...
```

**Comment by he0119** [comment]
如果把 filter_user 设置为 False 能看到吗？

```python
msgs = await get_message_records(
        session=session,
        filter_user=False,
        types=['message_sent'],
        time_start=datetime.now(timezone.utc) - timedelta(days=1),
    )
```

**Comment by zhtg-cxxc** [comment]
可以看到，感谢 :)
如果之后可以在参数解释里注明一下就更好了，感觉有 `filter_self_id` 在的情况下也不大会往 `filter_user` 去想。

**Comment by he0119** [comment]
目前文档确实只有一个简单的函数注释，以后看来还是得写详细点。
